# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: import.proto for package 'proto'

require 'grpc'
require 'import_pb'

module Proto
  module Harvester
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'proto.Harvester'

      rpc :Ver, Void, Version
      rpc :Import, stream(ImportInput), stream(ImportStats)
    end

    Stub = Service.rpc_stub_class
  end
end
